#!/bin/bash -x
source local
docker run -d \
--name mongoexpress \
--network cryptonetwork \
-p 8081:8081 \
-e ME_CONFIG_BASICAUTH_USERNAME=$BASICUSER \
-e ME_CONFIG_BASICAUTH_PASSWORD=$BASICPWD \
-e ME_CONFIG_MONGODB_ADMINUSERNAME=$ADMINUSER \
-e ME_CONFIG_MONGODB_ADMINPASSWORD=$ADMINPWD \
-e ME_CONFIG_MONGODB_PORT=$MONGOPORT \
-e ME_CONFIG_MONGODB_SERVER=$MONGOSERVERNAME \
--restart unless-stopped \
mongo-express
